### ISSUE TITLE
'pip install duckling' giving issue 

### ISSUE THREAD

**Issue by RachaRatan** [DongjunLee/kino-bot#28]
I want to install duckling to work on Rasa nlu training but it is giving issue as mentioned in below image please help me to fix this.

![image](https://user-images.githubusercontent.com/30255507/30155404-5b7ee606-93da-11e7-83c2-7c7585290c71.png)

**Comment by DongjunLee** [comment]
Hello @RachaRatan.
I don't know duckling and Rasa.

you already make same issue on stackoverflow.
maybe that is help you.
https://stackoverflow.com/questions/46092468/pip-install-duckling-giving-issue
